HospitalMvc/MvcApplication1/Controllers/ConsultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HospitalMVC.Models;
using System.ComponentModel.DataAnnotations;

namespace HospitalMVC.Controllers
{
    public class ConsultController : Controller
    {

        private ConsultDbContext _db = new ConsultDbContext();

  
        /// <summary>
        /// Allows generate a List of SelectListItems and put it in the ViewBag for utilization in the view.
        /// </summary>
   private void GenerateDoctorSelect()
        {
            List<SelectListItem> itemsDoc = new List<SelectListItem>();
            List<Doctor> listDoc = _db.Doctors.ToList();
            itemsDoc = listDoc.Select(d => new SelectListItem() { Text = d.Especialidad + ": " + d.Apellido + "," + d.Nombre, Value = "" + d.Matricula }).ToList();

            ViewBag.doctorList = itemsDoc;
        } 
        
        
        private void GenerateEspecialitySelect()
        {
            List<SelectListItem> itemsEsp = new List<SelectListItem>();

            var lisEsp = from d in _db.Doctors
                         select d.Especialidad;
            var listDoc = new List<string>();
            listDoc.AddRange(lisEsp.Distinct());

            itemsEsp = listDoc.Select(d => new SelectListItem() { Text = d, Value = d }).ToList();

            ViewBag.areaList = itemsEsp.Distinct();
        } 




     

        public ActionResult IndexList(String doctorList, String areaList )
        {
           
            GenerateDoctorSelect();
            GenerateEspecialitySelect();
        
            List<Consult> consultas = _db.Consults.OrderBy(d => d.Fecha).ToList();

  
            if (!String.IsNullOrEmpty(doctorList) && String.IsNullOrEmpty(areaList))
            {
                consultas = consultas.Where(s => s.Doctor.Matricula == Convert.ToInt32(doctorList)).ToList();
            }
            if (String.IsNullOrEmpty(doctorList) && !String.IsNullOrEmpty(areaList))
            {
                consultas = consultas.Where(s => s.Doctor.Especialidad.Equals(areaList)).ToList();
            }
                     
            
            return View(consultas);
        }

      
        public ActionResult Details(int id)
        {
            Consult consAux = _db.Consults.Find(id);
            consAux.Doctor = _db.Doctors.Find(consAux.DoctorId);
            return View(consAux);
        }

       

        public ActionResult Create()
        {
            GenerateDoctorSelect();

            return View();
        }

       

    
        [HttpPost]
        public ActionResult Create( Consult consulta, String doctorList)
        { 
            int matriculaDoc = Convert.ToInt32(doctorList);
            if (ModelState.IsValid)
            {
                 Doctor doc = _db.Doctors.Single(d => d.Matricula == matriculaDoc);
                 consulta.Doctor = doc;
                 _db.Consults.Add(consulta);
                _db.SaveChanges();
                return RedirectToAction("IndexList");
            }

            return View(consulta);
           
        }


        public ActionResult Delete(int id)
        {
            Consult consAux = _db.Consults.Find(id);
            return View(consAux);
        }



        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Consult consAux = _db.Consults.Find(id);
                _db.Consults.Remove(consAux);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

 
       
      
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }

      
}

HospitalMvc/MvcApplication1/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HospitalMVC.Models;

namespace HospitalMVC.Controllers
{ 
    public class DoctorsController : Controller
    {
        private ConsultDbContext _db = new ConsultDbContext();

      

        public ViewResult IndexList()
        {
            return View(_db.Doctors.ToList());
        }

       
        public ViewResult Details(int id)
        {
            Doctor doctor = _db.Doctors.Find(id);
            return View(doctor);
        }

       

        public ActionResult Create()
        {
            return View();
        } 

        

        [HttpPost]
        public ActionResult Create(Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _db.Doctors.Add(doctor);
                _db.SaveChanges();
                return RedirectToAction("IndexList");  
            }

            return View(doctor);
        }
        
        
 
        public ActionResult Edit(int id)
        {
            Doctor doctor = _db.Doctors.Find(id);
            return View(doctor);
        }

       
        [HttpPost]
        public ActionResult Edit(Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(doctor).State = EntityState.Modified;
                Doctor doc= _db.Doctors.Find(doctor.DoctorId);
                doc = doctor;
                _db.SaveChanges();
                return RedirectToAction("IndexList");
            }
            return View(doctor);
        }

       
 
        public ActionResult Delete(int id)
        {
            Doctor doctor = _db.Doctors.Find(id);
            return View(doctor);
        }

       

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Doctor doctor = _db.Doctors.Find(id);
            _db.Doctors.Remove(doctor);
            _db.SaveChanges();
            return RedirectToAction("IndexList");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HospitalMvc/MvcApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" rel="stylesheet"type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" rel="stylesheet" type="text/css" />
    
    <script src="../../Scripts/jquery-1.5.1.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Clinica Elquebrao</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Consultas clínicas", "IndexList", "Consult")</li>
                    <li>@Html.ActionLink("Doctores", "IndexList", "Doctors")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

HospitalMvc/MvcApplication1/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}